# Generated by Django 4.0 on 2021-12-30 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictData',
            fields=[
                ('picture', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='GoodPoint',
            fields=[
                ('text', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pictdata')),
            ],
        ),
        migrations.CreateModel(
            name='DetailGoodPoint',
            fields=[
                ('text', models.TextField()),
                ('clear_check', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goopo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.goodpoint')),
            ],
        ),
    ]
