# Generated by Django 4.0 on 2022-01-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_testmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailGoodPoint',
            new_name='MinuteGoodPoint',
        ),
    ]
