# Generated by Django 4.0 on 2022-01-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_delete_testmodel_rename_goopo_minutegoodpoint_gopo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictdata',
            name='picture',
            field=models.ImageField(upload_to='pictdata/'),
        ),
    ]
